### ISSUE TITLE
Fix BFS

### ISSUE THREAD

**Issue by webglider** [webglider/tartarus-examples#10]
- Rename to 'flooding' or something like that
- Change these to normal assertions: https://github.com/webglider/tartarus-examples/blob/master/Breadth%20First%20Search/bfs.pl#L9
- Add a example graph with more nodes that looks more like a tree
- Clean up the output made by agent if possible and add more delay.
- **TEST** it after you make any changes.

**Comment by codingant007** [comment]
Agent output is still messy. Remaining is done

**Comment by webglider** [comment]
(y)
I think you you need to update the README also

**Comment by codingant007** [comment]
you might be looking at the wrong folder.Look into `flooding` folder. I did update the readme. Tell me if you think anything more needs to be added.
