### ISSUE TITLE
Fix BST

### ISSUE THREAD

**Issue by webglider** [webglider/tartarus-examples#9]
- Change these to normal assertions: https://github.com/webglider/tartarus-examples/blob/master/Binary%20Search%20Tree/bst.pl#L19
- Attach a console and show step by step progress **NEATLY** Ref: https://github.com/webglider/tartarus-examples/blob/master/Depth%20First%20Search/explorer.pl#L13
- **TEST** it after making the changes

**Comment by codingant007** [comment]
Unlike earlier version the assertions of connections and values happen on individual platforms.
Console appears at 3 sec gap with seemingly neat output.
Tested thoroughly with many cases.
